link:../README.md[Back]

= Finance Questions

:toc:

== Accrued Interest ==

In accounting, `accrued interest` refers to the amount of interest that has been incurred, as of a specific date, on a loan or other financial obligation but has not yet been paid out. Accrued interest can either be in the form of accrued interest revenue, for the lender, or accrued interest expense, for the borrower. The term accrued interest can also refer to the amount of bond interest that has accumulated since the last time a bond interest payment was made.

== Bond ==

A bond is a fixed income instrument that represents a loan made by an investor to a borrower (typically corporate or governmental)

== Collateral ==

The term `collateral` refers to an asset that a lender accepts as security for a loan. Collateral may take the form of real estate or other kinds of assets, depending on the purpose of the loan. The collateral acts as a form of protection for the lender. That is, if the borrower defaults on their loan payments, the lender can seize the collateral and sell it to recoup some or all of its losses.

== Credit Risk ==

Credit risk is the possibility of losing a lender takes on due to the possibility of a borrower not paying back a loan. Consumer credit risk can be measured by the five Cs: credit history, capacity to repay, capital, the loan's conditions, and associated collateral.

== Derivative ==
 
A derivative is a financial security with a value that is reliant upon or derived from, an underlying asset or group of assets—a benchmark. The derivative itself is a contract between two or more parties, and the derivative derives its price from fluctuations in the underlying asset.

== Future Value (FV) ==

The FV calculation allows investors to predict, with varying degrees of accuracy, the amount of profit that can be generated by different investments. The amount of growth generated by holding a given amount in cash will likely be different than if that same amount were invested in stocks; so, the FV equation is used to compare multiple options.

== Futures ==

Futures are derivative financial contracts that obligate the parties to transact an asset at a predetermined future date and price. The buyer must purchase or the seller must sell the underlying asset at the set price, regardless of the current market price at the expiration date.

== Greeks ==

???????
 
== Haircut ==

A `haircut` has two meanings. The term haircut is most commonly used when referencing the percentage difference between an asset's market value and the amount that can be used as collateral for a loan. There is a difference between these values because market prices change over time, which the lender needs to accommodate for. For example, if a person needs a $10,000 loan and wants to use their $10,000 stock portfolio as collateral, the bank is likely to recognize the $10,000 portfolio as worth only $5,000 in collateral. The $5,000 or 50% reduction in the asset's value, for collateral purposes, is called the haircut.

== Holding Period ==

A holding period is the amount of time the investment is held by an investor, or the period between the purchase and sale of a security. In a long position, the holding period refers to the time between an asset's purchase and its sale. In a short options position, the holding period is the time between when a short seller buys back the securities and when the security is delivered to the lender to close the short position.

== Interest Rate Differential (IRD)

IRDs simply measure the difference in interest rates between two securities. If one bond yields 5% and another 3%, the IRD would be 2 percentage points—or 200 basis points (bps). IRD calculations are most often used in fixed income trading, forex trading, and lending calculations.

== Internal Revenue Service (IRS) ==
 
The Internal Revenue Service (IRS) is a U.S. government agency responsible for the collection of taxes and enforcement of tax laws

== Long Position ==

The term long position describes what an investor has purchased when they buy a security or derivative with the expectation that it will rise in value.

== Net Interest Rate Differential (NIRD) ==

The NIRD is the amount the investor can expect to profit using a carry trade. Say an investor borrows $1,000 and converts the funds into British pounds, allowing them to purchase a British bond. If the purchased bond yields 7% and the equivalent U.S. bond yields 3%, then the IRD equals 4%, or 7% minus 3%. This profit is ensured only if the exchange rate between dollars and pounds remains constant.

One of the primary risks involved with this strategy is the uncertainty of currency fluctuations. In this example, if the British pound were to fall in relation to the U.S. dollar, the trader may experience losses. Additionally, traders may use leverage, such as with a factor of 10-to-1, to improve their profit potential. If the investor leveraged borrowing by a factor of 10-to-1, they could make a profit of 40%. However, leverage could also cause larger losses if there are significant movements in exchange rates that go against the trade.

== Netting ==

`Netting` entails offsetting the value of multiple positions or payments due to be exchanged between two or more parties. It can be used to determine which party is owed remuneration in a multiparty agreement. Netting is a general concept that has a number of more specific uses, including in the financial markets.

== Notional ==

Notional value is a term often used to value the underlying asset in a derivatives trade. It can be the total value of a position, how much value a position controls, or an agreed-upon amount in a contract. This term is used when describing derivative contracts in the options, futures, and currency markets.

```js
Notional value = Contract size * underlying price
```

== Option ==

Options are financial instruments that are derivatives based on the value of underlying securities such as stocks. An options contract offers the buyer the opportunity to buy or sell—depending on the type of contract they hold—the underlying asset. Unlike futures, the holder is not required to buy or sell the asset if they choose not to.

 * Call options allow the holder to buy the asset at a stated price within a specific timeframe.
 * Put options allow the holder to sell the asset at a stated price within a specific timeframe.

== Present Value (PV) ==

Present value (PV) is the current value of a future sum of money or stream of cash flows given a specified rate of return. Future cash flows are discounted at the discount rate, and the higher the discount rate, the lower the present value of the future cash flows. Determining the appropriate discount rate is the key to properly valuing future cash flows, whether they be earnings or debt obligations.
 
== Sensitivity Analysis ==
 
A sensitivity analysis determines how different values of an independent variable affect a particular dependent variable under a given set of assumptions. In other words, sensitivity analyses study how various sources of uncertainty in a mathematical model contribute to the model's overall uncertainty. This technique is used within specific boundaries that depend on one or more input variables.

== Short (Short Position) ==

A short, or a short position, is created when a trader sells a security first with the intention of repurchasing it or covering it later at a lower price. A trader may decide to short a security when she believes that the price of that security is likely to decrease in the near future. There are two types of short positions: naked and covered. A naked short is when a trader sells a security without having possession of it.

However, that practice is illegal in the U.S. for equities. A covered short is when a trader borrows the shares from a stock loan department; in return, the trader pays a borrow-rate during the time the short position is in place.

== Tenor ==

Tenor refers to the length of time remaining before a financial contract expires. It is sometimes used interchangeably with the term maturity, although the terms have distinct meanings. Tenor is used in relation to bank loans, insurance contracts, and derivative products.
