link:../README.md[Back]

= Finance Questions =

== Interest Rate Differential (IRD) ==

IRDs simply measure the difference in interest rates between two securities. If one bond yields 5% and another 3%, the IRD would be 2 percentage points—or 200 basis points (bps). IRD calculations are most often used in fixed income trading, forex trading, and lending calculations.

== Net Interest Rate Differential (NIRD) ==

The NIRD is the amount the investor can expect to profit using a carry trade. Say an investor borrows $1,000 and converts the funds into British pounds, allowing them to purchase a British bond. If the purchased bond yields 7% and the equivalent U.S. bond yields 3%, then the IRD equals 4%, or 7% minus 3%. This profit is ensured only if the exchange rate between dollars and pounds remains constant.

One of the primary risks involved with this strategy is the uncertainty of currency fluctuations. In this example, if the British pound were to fall in relation to the U.S. dollar, the trader may experience losses. Additionally, traders may use leverage, such as with a factor of 10-to-1, to improve their profit potential. If the investor leveraged borrowing by a factor of 10-to-1, they could make a profit of 40%. However, leverage could also cause larger losses if there are significant movements in exchange rates that go against the trade.

== Internal Revenue Service (IRS) ==
 
The Internal Revenue Service (IRS) is a U.S. government agency responsible for the collection of taxes and enforcement of tax laws

== Bond ==

A bond is a fixed income instrument that represents a loan made by an investor to a borrower (typically corporate or governmental)


== Future Value (FV) ==
The FV calculation allows investors to predict, with varying degrees of accuracy, the amount of profit that can be generated by different investments. The amount of growth generated by holding a given amount in cash will likely be different than if that same amount were invested in stocks; so, the FV equation is used to compare multiple options.

== Present Value (PV) ==

Present value (PV) is the current value of a future sum of money or stream of cash flows given a specified rate of return. Future cash flows are discounted at the discount rate, and the higher the discount rate, the lower the present value of the future cash flows. Determining the appropriate discount rate is the key to properly valuing future cash flows, whether they be earnings or debt obligations.

== Greeks ==

 

== Short (Short Position) ==

A short, or a short position, is created when a trader sells a security first with the intention of repurchasing it or covering it later at a lower price. A trader may decide to short a security when she believes that the price of that security is likely to decrease in the near future. There are two types of short positions: naked and covered. A naked short is when a trader sells a security without having possession of it.

However, that practice is illegal in the U.S. for equities. A covered short is when a trader borrows the shares from a stock loan department; in return, the trader pays a borrow-rate during the time the short position is in place.

== Long Position ==

The term long position describes what an investor has purchased when they buy a security or derivative with the expectation that it will rise in value.

== Futures ==

Futures are derivative financial contracts that obligate the parties to transact an asset at a predetermined future date and price. The buyer must purchase or the seller must sell the underlying asset at the set price, regardless of the current market price at the expiration date.

== Option ==

Options are financial instruments that are derivatives based on the value of underlying securities such as stocks. An options contract offers the buyer the opportunity to buy or sell—depending on the type of contract they hold—the underlying asset. Unlike futures, the holder is not required to buy or sell the asset if they choose not to.

 * Call options allow the holder to buy the asset at a stated price within a specific timeframe.
 * Put options allow the holder to sell the asset at a stated price within a specific timeframe.
 
 == Sensitivity Analysis ==
 
A sensitivity analysis determines how different values of an independent variable affect a particular dependent variable under a given set of assumptions. In other words, sensitivity analyses study how various sources of uncertainty in a mathematical model contribute to the model's overall uncertainty. This technique is used within specific boundaries that depend on one or more input variables.
